services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # ← Используем dev версию
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
<<<<<<< HEAD
      - VITE_API_URL=http://backend:8000
    command: npm run dev -- --host
=======
      - VITE_API_URL=http://backend:8000  # ← Исправлено на backend
    command: npm run dev -- --host
>>>>>>> cfe9e6f43f0452ffa08c65e07119ec700ba26b77
